const CONTENT_DATA = [
  {
    id: '1',
    youtubeId: 'zjkBMFhNj_g',
    title: 'How LLMs Work',
    creator: '@karpathy',
    category: 'AI Foundations',
    xp: 500,
    guruTitle: 'LLM Guru',
    applicationScenario: {
      role: 'AI Consultant',
      context: 'A law firm wants to replace paralegals with an LLM. They trust it blindly. You must explain the limitations.',
    },
    challenges: [
      {
        id: 'c1_1',
        type: 'CONCEPT_CHECK',
        title: 'The Mechanism',
        prompt: 'Does an LLM "know" facts? Explain specifically how it generates the next word.',
        initialAiMessage: "I asked ChatGPT the capital of France and it got it right. That proves it has a database of facts, doesn't it?",
        required_concepts: [
          [
            { term: 'predict', synonyms: ['predicts', 'prediction', 'predicting', 'forecast'], weight: 3 },
            { term: 'probability', synonyms: ['probable', 'probabilistic', 'likely', 'likelihood', 'chance'], weight: 3 },
            { term: 'statistics', synonyms: ['statistical', 'statistically'], weight: 2 },
            { term: 'pattern', synonyms: ['patterns', 'pattern matching', 'learned patterns'], weight: 2 },
          ],
          [
            { term: 'next token', synonyms: ['next word', 'following word', 'continuation', 'sequence'], weight: 3 },
          ],
        ],
        forbidden_terms: [],
        min_word_count: 15,
        max_reading_level: null,
        xp_reward: 150,
        partial_xp_reward: 60,
        hint: 'Focus on the statistical nature of the output.',
      },
      {
        id: 'c1_2',
        type: 'TEACH_BACK',
        title: 'Guru Synthesis',
        prompt: 'Explain LLMs to a 5-year-old. Use an analogy. No technical jargon.',
        initialAiMessage: "I'm 5. I don't know what a 'neural net' is. How does the computer write stories?",
        required_concepts: [
          [
            { term: 'like a', synonyms: ['imagine', 'pretend', 'think of', 'similar to', 'just like', 'same as'], weight: 3 },
          ],
          [
            { term: 'guess', synonyms: ['guesses', 'guessing', 'fills in', 'completes', 'finishes', 'auto-complete', 'autocomplete'], weight: 3 },
            { term: 'story', synonyms: ['stories', 'sentences', 'words', 'book'], weight: 1 },
          ],
        ],
        forbidden_terms: [
          { term: 'transformer', hint: 'Use "smart helper" or "word machine" instead.' },
          { term: 'stochastic', hint: "Way too technical! Just say 'random' or 'guessing'." },
          { term: 'gradient', hint: "A 5-year-old doesn't know calculus!" },
          { term: 'vector', hint: 'Try "direction" or just skip this concept.' },
          { term: 'embedding', hint: 'Say "turning words into numbers" if needed.' },
          { term: 'neural', hint: 'Say "brain" or "smart computer" instead.' },
          { term: 'algorithm', hint: 'Say "recipe" or "set of steps" instead.' },
          { term: 'parameter', hint: 'Skip this — too technical for a 5-year-old.' },
        ],
        min_word_count: 20,
        max_reading_level: 7,
        xp_reward: 150,
        partial_xp_reward: 60,
        hint: "Use an analogy (e.g., 'auto-complete' or 'guessing game'). Don't use big words.",
      },
      {
        id: 'c1_3',
        type: 'APPLY',
        title: 'Real-World: Law Firm Risk',
        prompt: 'A law firm wants to replace paralegals with an LLM. They trust it blindly. As their AI consultant, explain specifically WHY this is risky and WHAT could go wrong.',
        initialAiMessage: "We just got GPT-4 access! We're firing our paralegals next week. The AI can do legal research perfectly, right? What could go wrong?",
        required_concepts: [
          [
            { term: 'hallucinate', synonyms: ['hallucination', 'make up', 'makes up', 'invents', 'fabricates', 'wrong', 'incorrect', 'false', 'inaccurate'], weight: 3 },
          ],
          [
            { term: 'verify', synonyms: ['check', 'review', 'validate', 'double check', 'fact check', 'human review', 'oversight'], weight: 3 },
          ],
          [
            { term: 'liability', synonyms: ['risk', 'danger', 'harm', 'lawsuit', 'malpractice', 'consequence', 'responsible', 'legal risk'], weight: 2 },
          ],
        ],
        forbidden_terms: [],
        min_word_count: 25,
        max_reading_level: null,
        xp_reward: 200,
        partial_xp_reward: 80,
        hint: 'Think about hallucinations, legal liability, and why human oversight is critical.',
      },
    ],
  },
  {
    id: '2',
    youtubeId: 'aircAruvnKk',
    title: 'Neural Networks',
    creator: '@3blue1brown',
    category: 'AI Foundations',
    xp: 500,
    guruTitle: 'Neural Net Guru',
    applicationScenario: { role: 'ML Engineer', context: 'Your CEO says "just add more layers" to fix a failing model. You need to explain why that might not help.' },
    challenges: [
      { id: 'c2_1', type: 'CONCEPT_CHECK', title: 'Layers & Learning', prompt: 'What does a hidden layer in a neural network actually do? How does it learn?', initialAiMessage: "I heard neural networks have layers like a cake. Does each layer memorize different facts?", required_concepts: [[{ term: 'weight', synonyms: ['weights', 'parameters', 'connections', 'adjusts', 'adjust'], weight: 3 }, { term: 'activation', synonyms: ['activations', 'neurons fire', 'output signal', 'nonlinear'], weight: 2 }], [{ term: 'feature', synonyms: ['features', 'representation', 'abstract', 'pattern', 'patterns', 'detect'], weight: 3 }]], forbidden_terms: [], min_word_count: 15, max_reading_level: null, xp_reward: 150, partial_xp_reward: 60, hint: 'Think about how each layer transforms data and detects patterns.' },
      { id: 'c2_2', type: 'TEACH_BACK', title: 'ELI5: Neural Nets', prompt: 'Explain neural networks to someone who has never coded. Use a real-world analogy.', initialAiMessage: "I'm a chef. I don't know what code is. How does the computer learn to recognize a cat photo?", required_concepts: [[{ term: 'like a', synonyms: ['imagine', 'pretend', 'think of', 'similar to', 'just like', 'same as', 'recipe'], weight: 3 }], [{ term: 'learn', synonyms: ['learns', 'learning', 'practice', 'practices', 'improve', 'improves', 'gets better', 'trains'], weight: 3 }]], forbidden_terms: [{ term: 'backpropagation', hint: 'Say "learning from mistakes" instead.' }, { term: 'gradient descent', hint: 'Say "adjusting step by step" instead.' }, { term: 'matrix', hint: 'Skip this — say "grid of numbers" if needed.' }, { term: 'tensor', hint: 'Way too technical. Skip it.' }, { term: 'epoch', hint: 'Say "round of practice" instead.' }, { term: 'loss function', hint: 'Say "score card" or "mistake counter" instead.' }], min_word_count: 20, max_reading_level: 7, xp_reward: 150, partial_xp_reward: 60, hint: 'Compare it to learning a skill through repetition and feedback.' },
      { id: 'c2_3', type: 'APPLY', title: 'Real-World: Failing Model', prompt: 'Your CEO says "just add more layers" to fix a failing image classifier. Explain WHY that probably won\'t work and WHAT they should actually do instead.', initialAiMessage: "Our cat/dog classifier is only 60% accurate. I told the ML team to just add 50 more layers. More layers = smarter AI, right? Why are they pushing back?", required_concepts: [[{ term: 'overfit', synonyms: ['overfitting', 'memorize', 'memorizes', 'too complex', 'complexity'], weight: 3 }, { term: 'data', synonyms: ['training data', 'dataset', 'more data', 'data quality', 'bad data', 'not enough data'], weight: 3 }], [{ term: 'instead', synonyms: ['should', 'better approach', 'what works', 'try', 'actually', 'the real issue', 'the problem is'], weight: 2 }]], forbidden_terms: [], min_word_count: 25, max_reading_level: null, xp_reward: 200, partial_xp_reward: 80, hint: 'Think about overfitting, data quality, and why more layers can actually hurt performance.' },
    ],
  },
  {
    id: '3',
    youtubeId: 'wjZofJX0v4M',
    title: 'Transformer Architecture',
    creator: '@3blue1brown',
    category: 'AI Deep Dive',
    xp: 575,
    guruTitle: 'Transformer Guru',
    applicationScenario: { role: 'AI Architect', context: 'Your team wants to build a custom model. They ask: should we use RNNs or Transformers? You need to explain the key difference.' },
    challenges: [
      { id: 'c3_1', type: 'CONCEPT_CHECK', title: 'Attention Mechanism', prompt: 'What is "attention" in transformers? Why was it a breakthrough over previous approaches?', initialAiMessage: "I know transformers replaced older models. But what exactly is 'attention' and why does it matter?", required_concepts: [[{ term: 'attention', synonyms: ['self-attention', 'attends to', 'focus on', 'focuses on', 'looks at all', 'weighs'], weight: 3 }], [{ term: 'parallel', synonyms: ['simultaneously', 'all at once', 'at the same time', 'concurrent', 'not sequential'], weight: 3 }, { term: 'context', synonyms: ['relationship', 'relationships', 'connections', 'relevant', 'relevance', 'related words'], weight: 2 }]], forbidden_terms: [], min_word_count: 20, max_reading_level: null, xp_reward: 175, partial_xp_reward: 70, hint: 'Think about how attention lets the model look at ALL words at once, not one by one.' },
      { id: 'c3_2', type: 'TEACH_BACK', title: 'ELI5: Attention', prompt: 'Explain the attention mechanism to a high school student. No math, just intuition.', initialAiMessage: "I'm in 10th grade. I heard AI uses 'attention' but that sounds like a human thing. What does it mean for a computer?", required_concepts: [[{ term: 'important', synonyms: ['matters', 'relevant', 'focus', 'focuses', 'pay attention', 'which parts'], weight: 3 }], [{ term: 'word', synonyms: ['words', 'sentence', 'text', 'meaning', 'reads'], weight: 1 }]], forbidden_terms: [{ term: 'query key value', hint: 'Say "the model asks what\'s important" instead.' }, { term: 'softmax', hint: 'Way too mathy. Say "picks the most relevant parts."' }, { term: 'dot product', hint: 'Say "measures similarity" or "compares words."' }, { term: 'multihead', hint: 'Say "looks at things from different angles."' }, { term: 'positional encoding', hint: 'Say "knows the order of words."' }], min_word_count: 20, max_reading_level: 9, xp_reward: 175, partial_xp_reward: 70, hint: 'Compare it to highlighting the most important words in a sentence.' },
      { id: 'c3_3', type: 'APPLY', title: 'Real-World: RNN vs Transformer', prompt: 'Your team asks: should we use RNNs or Transformers for our chatbot? Explain WHY transformers win for this use case and WHAT makes the difference.', initialAiMessage: "We have an old RNN-based chatbot. It works okay for short messages but falls apart on long conversations. Someone said transformers would fix this. Why? Aren't they just a newer version of the same thing?", required_concepts: [[{ term: 'parallel', synonyms: ['simultaneously', 'all at once', 'at the same time', 'not sequential', 'faster'], weight: 3 }], [{ term: 'long', synonyms: ['long-range', 'distant', 'far apart', 'long conversations', 'context window', 'remembers', 'forgets'], weight: 3 }], [{ term: 'sequential', synonyms: ['one by one', 'one at a time', 'step by step', 'slow', 'order', 'rnn limitation'], weight: 2 }]], forbidden_terms: [], min_word_count: 25, max_reading_level: null, xp_reward: 225, partial_xp_reward: 90, hint: 'Think about parallelism, long-range dependencies, and why RNNs struggle with long sequences.' },
    ],
  },
  {
    id: '4',
    youtubeId: '_bvrzYOA8dY',
    title: 'Prompt Engineering',
    creator: '@fireship',
    category: 'AI Skills',
    xp: 425,
    guruTitle: 'Prompt Guru',
    applicationScenario: { role: 'AI Product Manager', context: 'Your team is getting inconsistent outputs from GPT-4. Users complain the chatbot gives random answers. You need to fix the prompting strategy.' },
    challenges: [
      { id: 'c4_1', type: 'CONCEPT_CHECK', title: 'Prompt Design', prompt: 'Why does prompt structure matter? What makes a good prompt vs a bad one?', initialAiMessage: "I just type whatever I want into ChatGPT. Sometimes it works, sometimes it doesn't. Isn't it just luck?", required_concepts: [[{ term: 'specific', synonyms: ['specificity', 'clear', 'clarity', 'precise', 'detailed', 'explicit', 'instructions'], weight: 3 }], [{ term: 'context', synonyms: ['background', 'role', 'system prompt', 'examples', 'few-shot', 'few shot'], weight: 3 }, { term: 'structure', synonyms: ['structured', 'format', 'template', 'framework', 'step by step', 'chain of thought'], weight: 2 }]], forbidden_terms: [], min_word_count: 15, max_reading_level: null, xp_reward: 125, partial_xp_reward: 50, hint: 'Think about clarity, context-setting, and structured output.' },
      { id: 'c4_2', type: 'TEACH_BACK', title: 'ELI5: Prompting', prompt: 'Explain why prompt engineering matters to someone who just uses ChatGPT casually.', initialAiMessage: "I just ask ChatGPT stuff and it answers. Why would I need to learn special ways to ask?", required_concepts: [[{ term: 'ask', synonyms: ['question', 'request', 'tell', 'instruct', 'describe', 'explain to'], weight: 2 }], [{ term: 'better', synonyms: ['improved', 'accurate', 'useful', 'helpful', 'quality', 'good'], weight: 2 }, { term: 'answer', synonyms: ['response', 'output', 'result', 'reply', 'results'], weight: 1 }]], forbidden_terms: [{ term: 'token', hint: 'Say "word" or "piece of text" instead.' }, { term: 'temperature', hint: 'Say "randomness setting" or just "creativity dial."' }, { term: 'embedding', hint: 'Way too technical. Skip it.' }, { term: 'latent space', hint: 'No one casually knows this. Skip it.' }], min_word_count: 20, max_reading_level: 8, xp_reward: 125, partial_xp_reward: 50, hint: 'Compare it to asking a really smart person a vague question vs a specific one.' },
      { id: 'c4_3', type: 'APPLY', title: 'Real-World: Fix the Chatbot', prompt: 'Your company chatbot gives inconsistent answers. Users are frustrated. As AI Product Manager, explain WHY the prompts are failing and WHAT specific prompting strategy you would implement.', initialAiMessage: "Our customer support chatbot sometimes says we offer free returns, sometimes says we don't. Same question, different answers every time. The CEO is furious. How do we fix this?", required_concepts: [[{ term: 'system prompt', synonyms: ['system message', 'instructions', 'rules', 'constraints', 'guidelines', 'role'], weight: 3 }], [{ term: 'consistent', synonyms: ['consistency', 'reliable', 'same answer', 'predictable', 'stable', 'repeatable'], weight: 3 }], [{ term: 'example', synonyms: ['examples', 'few-shot', 'few shot', 'template', 'format', 'specify', 'specific'], weight: 2 }]], forbidden_terms: [], min_word_count: 25, max_reading_level: null, xp_reward: 175, partial_xp_reward: 70, hint: 'Think about system prompts, few-shot examples, and why vague prompts produce vague outputs.' },
    ],
  },
  {
    id: '5',
    youtubeId: 'jGwO_UgTS7I',
    title: 'AI Hallucinations',
    creator: '@IBMTechnology',
    category: 'AI Safety',
    xp: 500,
    guruTitle: 'AI Safety Guru',
    applicationScenario: { role: 'AI Safety Officer', context: 'A medical startup wants to use AI to diagnose patients. The AI sometimes confidently gives wrong answers. You must explain the risk.' },
    challenges: [
      { id: 'c5_1', type: 'CONCEPT_CHECK', title: 'Why AI Lies', prompt: 'Why do LLMs "hallucinate"? Why do they state false things with confidence?', initialAiMessage: "The AI sounded so sure when it gave a wrong answer. Does it know it's lying?", required_concepts: [[{ term: 'confidence', synonyms: ['confident', 'certainty', 'sure', 'convincing', 'plausible', 'fluent'], weight: 2 }, { term: 'no understanding', synonyms: ['doesnt understand', 'no knowledge', 'not aware', 'no awareness', 'doesnt know', 'cant tell'], weight: 3 }], [{ term: 'training data', synonyms: ['trained on', 'learned from', 'data it saw', 'patterns in data', 'statistical'], weight: 3 }]], forbidden_terms: [], min_word_count: 15, max_reading_level: null, xp_reward: 150, partial_xp_reward: 60, hint: "The model doesn't 'know' truth from fiction — it generates plausible-sounding text." },
      { id: 'c5_2', type: 'TEACH_BACK', title: 'ELI5: Hallucinations', prompt: 'Explain AI hallucinations to a non-technical manager who trusts ChatGPT completely.', initialAiMessage: "ChatGPT is always right though, isn't it? It sounds so professional. Why would I double-check it?", required_concepts: [[{ term: 'make up', synonyms: ['makes up', 'invents', 'fabricates', 'creates', 'generates', 'guesses', 'fills in gaps'], weight: 3 }], [{ term: 'check', synonyms: ['verify', 'double check', 'fact check', 'confirm', 'validate', 'review', 'trust but verify'], weight: 3 }]], forbidden_terms: [{ term: 'hallucinate', hint: 'They won\'t understand this term. Say "makes things up" or "invents facts."' }, { term: 'stochastic', hint: 'Say "random" or "unpredictable" instead.' }, { term: 'inference', hint: 'Say "when it generates an answer" instead.' }, { term: 'token', hint: 'Say "word" or "text" instead.' }], min_word_count: 20, max_reading_level: 8, xp_reward: 150, partial_xp_reward: 60, hint: 'Compare it to a confident student who makes up an answer rather than saying "I don\'t know."' },
      { id: 'c5_3', type: 'APPLY', title: 'Real-World: Medical AI Risk', prompt: 'A medical startup wants to use AI to diagnose patients. As their AI Safety Officer, explain WHY this is dangerous and WHAT safeguards must be in place.', initialAiMessage: "We trained a GPT model on medical textbooks. It diagnosed 3 test cases correctly! We want to launch it to real patients next month. Our investors love the idea. What's the hold up?", required_concepts: [[{ term: 'wrong', synonyms: ['incorrect', 'mistake', 'error', 'misdiagnose', 'false', 'inaccurate', 'hallucinate', 'make up'], weight: 3 }], [{ term: 'human', synonyms: ['doctor', 'physician', 'clinician', 'medical professional', 'oversight', 'review', 'verify'], weight: 3 }], [{ term: 'harm', synonyms: ['danger', 'risk', 'death', 'injury', 'patient safety', 'lives', 'life-threatening', 'liability'], weight: 3 }]], forbidden_terms: [], min_word_count: 30, max_reading_level: null, xp_reward: 200, partial_xp_reward: 80, hint: 'Think about patient safety, the difference between 3 test cases vs real-world deployment, and why human oversight is non-negotiable.' },
    ],
  },
  {
    id: '6',
    youtubeId: 'HkdAHXoRtos',
    title: 'Git for AI Projects',
    creator: '@fireship',
    category: 'AI Tooling',
    xp: 350,
    guruTitle: 'Version Control Guru',
    applicationScenario: { role: 'ML Ops Engineer', context: 'A junior ML engineer deleted a model training branch. They think the code and experiment results are gone forever.' },
    challenges: [
      { id: 'c6_1', type: 'CONCEPT_CHECK', title: 'Mental Model', prompt: 'Explain the difference between a Branch and a Commit Reference.', initialAiMessage: "Isn't a branch just a folder of files? When I switch branches, where do my files go?", required_concepts: [[{ term: 'pointer', synonyms: ['reference', 'label', 'sticky note', 'bookmark', 'points to', 'refers to'], weight: 3 }], [{ term: 'snapshot', synonyms: ['hash', 'history', 'commit', 'save point', 'checkpoint', 'record'], weight: 2 }]], forbidden_terms: [], min_word_count: 15, max_reading_level: null, xp_reward: 100, partial_xp_reward: 40, hint: 'A branch is just a movable pointer to a commit.' },
      { id: 'c6_2', type: 'APPLY', title: 'Real-World: Deleted Branch', prompt: 'A junior ML engineer deleted a training branch with weeks of experiment results. They think everything is lost forever. Explain WHY the work is NOT gone and HOW to recover it.', initialAiMessage: "I accidentally ran 'git branch -D experiments' and now all my training configs and results are gone! I didn't push it anywhere. It's been 2 weeks of work. Is there any way to get it back?", required_concepts: [[{ term: 'reflog', synonyms: ['ref log', 'git reflog', 'log', 'history', 'still there', 'not deleted'], weight: 3 }], [{ term: 'commit', synonyms: ['commits', 'committed', 'hash', 'sha', 'snapshot', 'saved'], weight: 2 }]], forbidden_terms: [], min_word_count: 20, max_reading_level: null, xp_reward: 150, partial_xp_reward: 60, hint: 'Git reflog keeps a record of where HEAD has been. Commits are not immediately garbage collected.' },
    ],
  },
  {
    id: '7',
    youtubeId: 'Tn6-PIqc4UM',
    title: 'React for AI Apps',
    creator: '@fireship',
    category: 'AI Tooling',
    xp: 425,
    guruTitle: 'AI Frontend Guru',
    applicationScenario: { role: 'AI Frontend Engineer', context: 'You\'re building a ChatGPT-like interface. The app freezes on every keystroke while streaming AI responses. Users are complaining.' },
    challenges: [
      { id: 'c7_1', type: 'CONCEPT_CHECK', title: 'Virtual DOM', prompt: 'Why do we need a Virtual DOM? Why is direct DOM manipulation slow for AI chat UIs?', initialAiMessage: "The browser already has a DOM. Why add another layer? Isn't that making things slower?", required_concepts: [[{ term: 'batch', synonyms: ['batching', 'batches', 'groups', 'combines', 'collects', 'gathers'], weight: 3 }, { term: 'diff', synonyms: ['diffing', 'compare', 'comparison', 'reconciliation', 'reconcile', 'checks what changed'], weight: 3 }], [{ term: 'repaint', synonyms: ['reflow', 'expensive', 'slow', 'layout', 're-render', 'redraw', 'costly'], weight: 2 }]], forbidden_terms: [], min_word_count: 20, max_reading_level: null, xp_reward: 125, partial_xp_reward: 50, hint: "Talk about 'batching' updates or 'diffing' changes." },
      { id: 'c7_2', type: 'TEACH_BACK', title: 'ELI5: React', prompt: 'Explain React re-rendering to someone who only knows HTML and wants to build AI tools.', initialAiMessage: "I know HTML. I make web pages. Why do I need this React thing to build an AI chatbot?", required_concepts: [[{ term: 'update', synonyms: ['updates', 'changes', 'change', 'refresh', 'modify', 'auto'], weight: 3 }], [{ term: 'page', synonyms: ['screen', 'display', 'view', 'website', 'app', 'interface'], weight: 1 }]], forbidden_terms: [{ term: 'virtual dom', hint: 'Just say "it keeps a draft copy" or "blueprint".' }, { term: 'reconciliation', hint: 'Way too technical. Say "figures out what changed".' }, { term: 'fiber', hint: 'Skip this — say "it works in small steps".' }, { term: 'jsx', hint: 'Say "HTML-like code" or "template".' }], min_word_count: 20, max_reading_level: 8, xp_reward: 125, partial_xp_reward: 50, hint: 'Compare it to reloading vs. surgically updating parts of the page.' },
      { id: 'c7_3', type: 'APPLY', title: 'Real-World: Freezing Chat UI', prompt: 'Your ChatGPT-like interface freezes on every keystroke while streaming AI responses. Explain WHY this happens and WHAT React patterns would fix it.', initialAiMessage: "Our AI chat app locks up completely when the AI is streaming a long response. Users can't even scroll or type. Our React code re-renders everything on each new token. Help!", required_concepts: [[{ term: 're-render', synonyms: ['rerender', 'rendering', 'renders', 'render cycle', 'unnecessary render', 'too many renders'], weight: 3 }], [{ term: 'memo', synonyms: ['memoize', 'memoization', 'useMemo', 'useCallback', 'React.memo', 'cache', 'skip'], weight: 3 }, { term: 'virtualize', synonyms: ['virtualization', 'virtual list', 'windowing', 'FlatList', 'only visible'], weight: 2 }]], forbidden_terms: [], min_word_count: 25, max_reading_level: null, xp_reward: 175, partial_xp_reward: 70, hint: 'Think about memoization (React.memo, useMemo), list virtualization, and isolating re-renders.' },
    ],
  },
];

export default CONTENT_DATA;
